- tracking.mailchimp.com
- click.sendgrid.net
- trk.klaviyo.com
- open.convertkit.com
- t.dripemail.com
- links.hubspot.com
- pixel.hubspot.com
- t.sidekickopen.com
- track.customer.io
- email.eg.e.klaviyo.com
- trk.emaildelivery.com
- open.mail.com
- mailtrack.io
- t.yesware.com
- t.salesforce.com
