source "https://rubygems.org"

gem "rails", "~> 8.1.3", ">= 8.1.3.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# Auth
gem "bcrypt", "~> 3.1.7"
gem "jwt"

# Mail
gem "mail_room"

# HTTP & Parsing
gem "faraday"
gem "nokogiri"
gem "feedjira"

# Background jobs
gem "sidekiq"

# Rate limiting
gem "rack-attack"

# CORS
gem "rack-cors"

# Encryption (for API keys)
gem "attr_encrypted", "~> 4.0"

# 2FA
gem "rotp"
gem "rqrcode"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "dotenv-rails"
end

gem "kramdown", "~> 2.5"
